import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import getCurrentUser from "./actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const currentUser = await getCurrentUser();
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar currentUser={currentUser} />
				<div className="lg:max-w-[900px] lg:px-16 mx-auto py-8 min-h-screen flex  flex-col px-8">
					<div className="flex-auto">{children}</div>
					<Footer />
				</div>
			</body>
		</html>
	);
}
